import Head from 'next/head'
import Image from "next/image"
import { useRouter } from 'next/router'

export default function Home({movies}) {
const router = useRouter()

const goTopage = (id) => {
   router.push(`/${id}`)
}

  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Image src="https://images-na.ssl-images-amazon.com/images/M/MV5BN2EyYzgyOWEtNTY2NS00NjRjLWJiNDYtMWViMjg5MWZjYjgzXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg" alt="pic" width={100} height={100} /> */}
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"12px",marginTop:"40px"}}>
        {movies?.map((item)=>{
          return (
            <div style={{border:"1px solid white",textAlign:"center"}} key={item.id}>
              <img src={item.Images} alt={item.Title} width={100} height={100} />
                <h2>{item.Title}</h2>
               <button onClick={()=>goTopage(item.id)}>See Details</button>
            </div>
          )
        })}
      </div>
    </>
  )
}

export async function getStaticProps(){
  let res = await fetch(`https://movies-database-gold.vercel.app/movies`)
  let data = await res.json()
  return {
    props : {
      movies : data
    }
  }
}
